-- Run as SYSDBA (OS authentication: sqlplus / as sysdba) on the project VM.
-- Creates the schema owner inside the CS5322 pluggable database. Safe to re-run:
-- an existing account keeps its objects, but its password is reset and unlocked.
ALTER SESSION SET CONTAINER = CS5322;

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM dba_users WHERE username = 'CS5322_P1';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER CS5322_P1 IDENTIFIED BY "CS5322#2026"';
    ELSE
        EXECUTE IMMEDIATE 'ALTER USER CS5322_P1 IDENTIFIED BY "CS5322#2026" ACCOUNT UNLOCK';
    END IF;
END;
/

GRANT CREATE SESSION, RESOURCE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER TO CS5322_P1;
GRANT CREATE ANY CONTEXT TO CS5322_P1;
GRANT EXECUTE ON DBMS_RLS TO CS5322_P1;
ALTER USER CS5322_P1 QUOTA UNLIMITED ON SYSTEM;
ALTER USER CS5322_P1 QUOTA UNLIMITED ON USERS;
