-- Prints the predicate each policy function returns for a given identity: this is the text
-- Oracle appends (with AND) to every statement on the protected table.
-- Run as CS5322_P1 after 03_vpd_policies.sql.  Useful in the demonstration to show *how*
-- a policy works, and the source of the predicate table in the report.
SET SERVEROUTPUT ON SIZE UNLIMITED
SET FEEDBACK OFF
SET LINESIZE 700
SET TRIMSPOOL ON

PROMPT === Predicates generated by the policy functions ===
DECLARE
    PROCEDURE show(p_user VARCHAR2, p_policy VARCHAR2, p_fn VARCHAR2) IS
        v_pred VARCHAR2(4000);
    BEGIN
        IF p_user IS NULL THEN
            cs5322_security_ctx.clear_user;
        ELSE
            cs5322_security_ctx.set_user(p_user);
        END IF;
        EXECUTE IMMEDIATE 'BEGIN :p := ' || p_fn || '(''CS5322_P1'', ''X''); END;' USING OUT v_pred;
        DBMS_OUTPUT.PUT_LINE('PREDICATE | ' || NVL(p_user, '(no identity)') || ' | ' || p_policy || ' | ' || v_pred);
    END;
BEGIN
    show('alice',      'STUDENT_VPD',            'student_vpd_fn');
    show('alice',      'GRADE_VPD',              'grade_vpd_fn');
    show('prof_lee',   'STUDENT_VPD',            'student_vpd_fn');
    show('prof_lee',   'GRADE_WRITE_VPD',        'grade_write_fn');
    show('prof_lee',   'ROOM_ALLOCATION_VPD',    'room_allocation_vpd_fn');
    show('admin_comp', 'STUDENT_VPD',            'student_vpd_fn');
    show('admin_comp', 'SECTION_VPD',            'section_vpd_fn');
    show('admin_comp', 'GRADE_DELETE_VPD',       'grade_delete_fn');
    show('finance1',   'STUDENT_VPD',            'student_vpd_fn');
    show('finance1',   'STUDENT_EMAIL_MASK_VPD', 'student_email_mask_fn');
    show('housing1',   'STUDENT_VPD',            'student_vpd_fn');
    show('uni_admin',  'GRADE_VPD',              'grade_vpd_fn');
    show(NULL,         'GRADE_VPD',              'grade_vpd_fn');
    cs5322_security_ctx.clear_user;
END;
/
