-- Run as SYSDBA against the FREEPDB1 pluggable database.
ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER CS5322_P1 IDENTIFIED BY "CS5322#2026";
GRANT CREATE SESSION, RESOURCE, CREATE VIEW, CREATE PROCEDURE TO CS5322_P1;
GRANT CREATE ANY CONTEXT TO CS5322_P1;
GRANT EXECUTE ON DBMS_RLS TO CS5322_P1;
ALTER USER CS5322_P1 QUOTA UNLIMITED ON SYSTEM;
